name: Close Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'Cette issue est inactive depuis 30 jours. Elle sera fermée dans 7 jours si aucune activité n\'est détectée.'
          stale-pr-message: 'Cette Pull Request est inactive depuis 30 jours. Elle sera fermée dans 7 jours si aucune activité n\'est détectée.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
